main/urls.py
from django.urls import path, include
from main import views

app_name = 'main'
urlpatterns = [
    path('login/', views.Login.as_view(), name = 'login'),
    path('top/', views.Top.as_view(), name = 'top'),
    path('logout/', views.Logout.as_view(), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),
    path('', views.ListCompany.as_view(), name = 'list_company'),
    path('companies/<int:pk>', views.DetailCompany.as_view(), name = 'detail_company'),
    path('profile/<int:pk>', views.Profile.as_view(), name = 'profile'),
]

main/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from datetime import datetime

from django.core.validators import (
    RegexValidator, MaxValueValidator, MinValueValidator
)

# Create your models here.
class UserManager(BaseUserManager):
    """ユーザーマネージャー."""
    
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

category1s = [
    ('IT', 'IT'),
    ('ART', 'アート・デザイン'),
    ('CONTENTS', 'コンテンツ'),
    ('LIFE', 'ライフサポート'),
    ('OTHER', 'その他'),
]
category2s = [
    ("HP", "ホームページ作成"),
    ("SYSTEM", "システム製作"),
    ("PRINT", "印刷物デザイン"),
    ("GRAPHIC", "グラフィックデザイン"),
    ("ILLUST", "イラスト作成,撮影（写真）"),
    ("MOVIE", "撮影（映像）"),
    ("EDITING", "編集"),
    ("DTP", "DTP"),
    ("AUDIO", "音声収録"),
    ("EVNT-PLN", "イベント企画"),
    ("EVNT-SETUP", "イベント設営"),
    ("SALES", "営業支援"),
    ("SW", "ソフトウェア開発"),
    ("TRANSL", "翻訳・通訳"),
    ("CNSL", "コンサルティング"),
    ("WRT", "文章ライティング"),
    ("INTVW", "取材"),
    ("NW", "ネットワーク施工"),
    ("SVR", "サーバ関連"),
    ("LAW", "法務"),
    ("LABR", "労務"),
    ("ACCNT", "財務・会計"),
    ("GAME", "ゲーム製作"),
    ("MED", "医療"),
    ("CARE", "介護"),
    ('OTHER', 'その他'),
]
def get_years():
    this_year = datetime.today().year
    ys = []
    for i in range(100):
        y = str(this_year - i)
        ys.append((y, y))
    return ys

class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = '登録企業'
        verbose_name_plural = '登録企業'
    def __str__(self):
        return self.username
    email = models.EmailField(_('Email'), unique=True)
    company_name = models.CharField(
        verbose_name = '社名',
        max_length = 255
    )
    company_name_furigana = models.CharField(
        verbose_name = '会社名フリガナ',
        max_length = 255,
    )
    thumbnail = models.ImageField(
        verbose_name = 'サムネイル',
        null = True,
        blank = True,
        upload_to = 'thumbnail/'
    )
    category1 = models.CharField(
        verbose_name = '業種（大分類）',
        max_length = 100,
        choices = category1s
    )
    @property
    def category1_name(self):
        if not self.category1:
            return ''
        cat = [e for e in category1s if e[0] == self.category1]
        if len(cat) > 0:
            return cat[0][1]
        else:
            return ''
    category2 = models.CharField(
        verbose_name = '業種（小分類）',
        max_length = 100,
        choices=category2s
    )
    @property
    def category2_name(self):
        if not self.category2:
            return ''
        cat = [e for e in category2s if e[0] == self.category2]
        if len(cat) > 0:
            return cat[0][1]
        else:
            return ''

    short_description = models.TextField(
        verbose_name = '会社概要',
    )
    description = models.TextField(
        verbose_name = '業務内容説明',
    )
    phone = models.CharField(
        verbose_name = '電話番号',
        max_length = 100,
        validators = [
            RegexValidator(
                regex = '[0-9\-\+]+',
                message = 'フォーマットが不正です。'
            )
        ]
    )
    short_delivery = models.BooleanField(
        verbose_name = '短納期対応可',
        default = False
    )
    representative_name = models.CharField(
        verbose_name = '代表者名',
        max_length = 255,
        blank = True,
        default=""
    )
    established_at = models.CharField(
        verbose_name = '創業',
        max_length = 100,
        choices = get_years()
    )

    major_clients = models.TextField(
        verbose_name = '主な取引先',
        blank = True,
    )
    major_products = models.TextField(
        verbose_name = '主な製品',
        blank = True,
    )
    major_technologies = models.TextField(
        verbose_name = '主な技術',
        blank = True,
    )
    major_facilities = models.TextField(
        verbose_name = '主な施設',
        blank = True,
    )
    appeal_points = models.CharField(
        verbose_name = 'アピールポイント',
        blank = True,
        default="",
        max_length = 255,
    )
    poc_name = models.CharField(
        verbose_name = '担当者名',
        blank = True,
        default="",
        max_length = 100
    )
    website = models.URLField(
        blank = True,
        default="",
        verbose_name = 'website'
    )

    
    is_staff = models.BooleanField(
        _('管理者'),
        default=False,
        help_text=_(
        'Designates whether the user can log into this admin site.'),
    )
    is_superuser = models.BooleanField(
        _('スーパーユーザ'),
        default=False,
        help_text=_(
        'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('利用開始'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    @property
    def username(self):
        """username属性のゲッター
        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

main/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm
)
from django import forms
from .models import (
    User,
    category1s,
    category2s
)

form_input_base_class = 'p-2 form-input block border w-full mb-2'

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class': form_input_base_class,
            }
        )
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs = {
                'class': form_input_base_class,
            }
    )
)

class SignUpForm(UserCreationForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = [
            'email',
            'company_name',
            'company_name_furigana',
            'thumbnail', 
            'category1', 
            'category2',
            'short_description',
            'description',
            'phone',
            'short_delivery',
            'representative_name',
            'established_at',
            'major_clients',
            'major_products',
            'major_technologies',
            'major_facilities',
            'appeal_points',
            'poc_name',
            'website',
            'password1', 
            'password2', 
        ]
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

class ProfileForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = (
            'company_name', 
            'company_name_furigana',
            'thumbnail',
            'category1', 
            'category2',
            'short_description',
            'description',
            'phone',
            'short_delivery',
            'representative_name',
            'established_at',
            'major_clients',
            'major_products',
            'major_technologies',
            'major_facilities',
            'appeal_points',
            'poc_name',
            'website',
        )
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.required:
                visible.field.label = f'{visible.field.label}*'
            visible.field.widget.attrs['class'] = form_input_base_class

class PasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

main/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.contrib.auth.mixins import (
    UserPassesTestMixin, LoginRequiredMixin
)
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.views.generic import (
    CreateView, UpdateView, TemplateView, ListView, DeleteView, DetailView
)
from django.urls import reverse_lazy
from django.contrib import messages

from .forms import (
    LoginForm, ProfileForm, SignUpForm, PasswordForm
)
from .models import (
    User,
)

from django.contrib.auth.mixins import UserPassesTestMixin


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True     # set True if raise 403_Forbidden

    def test_func(self):
        user = self.request.user
        if not user.is_authentiated:
            return False
        return user.pk == self.kwargs['pk'] or user.is_superuser



# Create your views here.
class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'main/login.html'

class Top(LoginRequiredMixin, TemplateView):
    template_name = 'main/top.html'

    def get(self, request):
        return redirect('main:profile', request.user.pk)

class Logout(LogoutView):
    pass

    
class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy('main:login')
    template_name = 'main/signup.html'
    
    def form_valid(self, form):
        ret = super().form_valid(form)
        messages.success(self.request, f'ユーザ:{self.object.username} 登録完了しました。')
        return ret

from .models import category1s, category2s
class ListCompany(ListView):
    model = User
    template_name = 'main/list_company.html'
    paginate_by = 3
    
    def get_context_data(self, **kwargs):
        total_count = self.get_queryset().count()
        c = super().get_context_data(**kwargs)
        c['total_count'] = total_count
        c['category1s'] = category1s
        c['category2s'] = category2s
        c1 = self.request.GET.getlist('category1s')
        c2 = self.request.GET.getlist('category2s')
        c['query_params'] = { 
            'category1s': c1,
            'category2s': c2,
            'query': self.request.GET.get('query', '')
        }
        print(c['total_count'])
        return c

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-pk')
        c1 = self.request.GET.getlist('category1s')
        c2 = self.request.GET.getlist('category2s')
        query = self.request.GET.get('query', None)
        if len(c1) > 0:
            queryset = queryset.filter(category1__in = c1)
        if len(c2) > 0:
            queryset = queryset.filter(category2__in = c2)
        if query:
            queryset = queryset.filter(company_name__icontains = query)
        return queryset

class DetailCompany(DetailView):
    model = User
    template_name = 'main/detail_company.html'
    
class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm   
    template_name = 'main/profile.html'
    def get_success_url(self):
        return reverse_lazy('main:profile', kwargs={ "pk": self.kwargs["pk"] })
    
    def form_valid(self, form):
        messages.success(self.request, '登録情報を更新しました')
        return super().form_valid(form)

main/templates/main/components/footer.html
{% load static %}
<div class="text-center">
    <footer class="text-white py-5" style="background-color: #192024;">
        <div class="flex mb-5">
            <img class="h-8" src="{% static 'img/logo_w.svg' %}" alt="">
            <div class="text-sm text-left ml-3">
                ビジネスマッチング＆コワーキングスペース<br>
                創業支援も充実している東京中野の「ictco（イクトコ）」
            </div>
        </div>
        <div class="text-left text-sm ">
            一般社団法人 中野区産業振興推進機構 〒164-0001 東京都中野区中野4-10-1 NAKANO CENTRAL PARK EAST 1F
        </div>
    </footer>
</div>

main/templates/main/components/navbar.html
{% load static %}
<nav class="flex items-center justify-between flex-wrap bg-white-500 p-6 border-b-4 border-black">
    <div class="flex items-center flex-shrink-0 text-black mr-6">
        <img class="h-11" src="{% static 'img/logo.png' %}" alt="">
    </div>
    <div class="block md:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-black border-black hover:text-black hover:border-white navbar-burger">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
    </div>
    <div class="w-full block flex-grow md:flex md:justify-end md:w-auto hidden" id="main-nav">
        <div>
            {% if user.is_authenticated %}
            <a href="{% url 'main:list_company' %}" class="block md:inline-block text-sm px-4 py-2 leading-none rounded text-black border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 md:mt-0">サイト閲覧</a>
            <a href="{% url 'main:profile' user.pk %}" class="block md:inline-block text-sm px-4 py-2 leading-none rounded text-black border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 md:mt-0">登録情報変更</a>
            <a href="{% url 'main:logout' %}" class="block md:inline-block text-sm px-4 py-2 leading-none rounded text-black border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 md:mt-0">ログアウト</a>
            {% else %}
            <a href="{% url 'main:login' %}" class="block md:inline-block text-sm px-4 py-2 leading-none rounded text-black border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 md:mt-0">会員企業様ログイン</a>
            {% endif %}
        </div>
    </div>
</nav>
<script>
    document.addEventListener('DOMContentLoaded', function () {
    // Get all "navbar-burger" elements
    var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach(function ($el) {
            $el.addEventListener('click', function () {
                // Get the "main-nav" element
                var $target = document.getElementById('main-nav');
                // Toggle the class on "main-nav"
                $target.classList.toggle('hidden');

                });
            });
        }

    });
</script>

main/templates/main/components/paginator.html
<nav aria-label="Page navigation example">
    <ul class="flex">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="">
                <a class="" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="ml-1 text-gray-400 active"><a class="border-b-2 border-green-600 " href="#">{{ num }}</a></li>
                {% else %}
                    <li class="ml-1"><a class="text-green-600" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="ml-1">
                <a class="" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

main/templates/main/components/short_delivery.html
<div class="bg-red-600 p-2 text-white font-bold rounded-lg">
    短納期可
</div>