main/urls.py
from django.urls import path, include
from main import views

app_name = 'main'
urlpatterns = [
    path('login/', views.Login.as_view(), name = 'login'),
    path('top/', views.Top.as_view(), name = 'top'),
    path('logout/', views.Logout.as_view(), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),
    path('', views.ListCompany.as_view(), name = 'list_company'),
    path('companies/<int:pk>', views.DetailCompany.as_view(), name = 'detail_company'),
    path('profile/<int:pk>', views.Profile.as_view(), name = 'profile'),
]

main/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from datetime import datetime

from django.core.validators import (
    RegexValidator, MaxValueValidator, MinValueValidator
)

# Create your models here.
class UserManager(BaseUserManager):
    """ユーザーマネージャー."""
    
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

category1s = [
    ('IT', 'IT'),
    ('ART', 'アート・デザイン'),
    ('CONTENTS', 'コンテンツ'),
    ('LIFE', 'ライフサポート'),
    ('OTHER', 'その他'),
]
category2s = [
    ("HP", "ホームページ作成"),
    ("SYSTEM", "システム製作"),
    ("PRINT", "印刷物デザイン"),
    ("GRAPHIC", "グラフィックデザイン"),
    ("ILLUST", "イラスト作成,撮影（写真）"),
    ("MOVIE", "撮影（映像）"),
    ("EDITING", "編集"),
    ("DTP", "DTP"),
    ("AUDIO", "音声収録"),
    ("EVNT-PLN", "イベント企画"),
    ("EVNT-SETUP", "イベント設営"),
    ("SALES", "営業支援"),
    ("SW", "ソフトウェア開発"),
    ("TRANSL", "翻訳・通訳"),
    ("CNSL", "コンサルティング"),
    ("WRT", "文章ライティング"),
    ("INTVW", "取材"),
    ("NW", "ネットワーク施工"),
    ("SVR", "サーバ関連"),
    ("LAW", "法務"),
    ("LABR", "労務"),
    ("ACCNT", "財務・会計"),
    ("GAME", "ゲーム製作"),
    ("MED", "医療"),
    ("CARE", "介護"),
    ('OTHER', 'その他'),
]
def get_years():
    this_year = datetime.today().year
    ys = []
    for i in range(100):
        y = str(this_year - i)
        ys.append((y, y))
    return ys

class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = '登録企業'
        verbose_name_plural = '登録企業'
    def __str__(self):
        return self.username
    email = models.EmailField(_('Email'), unique=True)
    company_name = models.CharField(
        verbose_name = '社名',
        max_length = 255
    )
    company_name_furigana = models.CharField(
        verbose_name = '会社名フリガナ',
        max_length = 255,
    )
    thumbnail = models.ImageField(
        verbose_name = 'サムネイル',
        null = True,
        blank = True,
        upload_to = 'thumbnail/'
    )
    category1 = models.CharField(
        verbose_name = '業種（大分類）',
        max_length = 100,
        choices = category1s
    )
    @property
    def category1_name(self):
        if not self.category1:
            return ''
        cat = [e for e in category1s if e[0] == self.category1]
        if len(cat) > 0:
            return cat[0][1]
        else:
            return ''
    category2 = models.CharField(
        verbose_name = '業種（小分類）',
        max_length = 100,
        choices=category2s
    )
    @property
    def category2_name(self):
        if not self.category2:
            return ''
        cat = [e for e in category2s if e[0] == self.category2]
        if len(cat) > 0:
            return cat[0][1]
        else:
            return ''

    short_description = models.TextField(
        verbose_name = '会社概要',
    )
    description = models.TextField(
        verbose_name = '業務内容説明',
    )
    phone = models.CharField(
        verbose_name = '電話番号',
        max_length = 100,
        validators = [
            RegexValidator(
                regex = '[0-9\-\+]+',
                message = 'フォーマットが不正です。'
            )
        ]
    )
    short_delivery = models.BooleanField(
        verbose_name = '短納期対応可',
        default = False
    )
    representative_name = models.CharField(
        verbose_name = '代表者名',
        max_length = 255,
        blank = True,
        default=""
    )
    established_at = models.CharField(
        verbose_name = '創業',
        max_length = 100,
        choices = get_years()
    )

    major_clients = models.TextField(
        verbose_name = '主な取引先',
        blank = True,
    )
    major_products = models.TextField(
        verbose_name = '主な製品',
        blank = True,
    )
    major_technologies = models.TextField(
        verbose_name = '主な技術',
        blank = True,
    )
    major_facilities = models.TextField(
        verbose_name = '主な施設',
        blank = True,
    )
    appeal_points = models.CharField(
        verbose_name = 'アピールポイント',
        blank = True,
        default="",
        max_length = 255,
    )
    poc_name = models.CharField(
        verbose_name = '担当者名',
        blank = True,
        default="",
        max_length = 100
    )
    website = models.URLField(
        blank = True,
        default="",
        verbose_name = 'website'
    )

    
    is_staff = models.BooleanField(
        _('管理者'),
        default=False,
        help_text=_(
        'Designates whether the user can log into this admin site.'),
    )
    is_superuser = models.BooleanField(
        _('スーパーユーザ'),
        default=False,
        help_text=_(
        'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('利用開始'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    @property
    def username(self):
        """username属性のゲッター
        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

main/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm
)
from django import forms
from .models import (
    User,
    category1s,
    category2s
)

form_input_base_class = 'p-2 form-input block border w-full mb-2'

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class': form_input_base_class,
            }
        )
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs = {
                'class': form_input_base_class,
            }
    )
)

class SignUpForm(UserCreationForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = [
            'email',
            'company_name',
            'company_name_furigana',
            'thumbnail', 
            'category1', 
            'category2',
            'short_description',
            'description',
            'phone',
            'short_delivery',
            'representative_name',
            'established_at',
            'major_clients',
            'major_products',
            'major_technologies',
            'major_facilities',
            'appeal_points',
            'poc_name',
            'website',
            'password1', 
            'password2', 
        ]
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

class ProfileForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = (
            'company_name', 
            'company_name_furigana',
            'thumbnail',
            'category1', 
            'category2',
            'short_description',
            'description',
            'phone',
            'short_delivery',
            'representative_name',
            'established_at',
            'major_clients',
            'major_products',
            'major_technologies',
            'major_facilities',
            'appeal_points',
            'poc_name',
            'website',
        )
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.required:
                visible.field.label = f'{visible.field.label}*'
            visible.field.widget.attrs['class'] = form_input_base_class

class PasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

main/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.contrib.auth.mixins import (
    UserPassesTestMixin, LoginRequiredMixin
)
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.views.generic import (
    CreateView, UpdateView, TemplateView, ListView, DeleteView, DetailView
)
from django.urls import reverse_lazy
from django.contrib import messages

from .forms import (
    LoginForm, ProfileForm, SignUpForm, PasswordForm
)
from .models import (
    User,
)

from django.contrib.auth.mixins import UserPassesTestMixin


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True     # set True if raise 403_Forbidden

    def test_func(self):
        user = self.request.user
        if not user.is_authentiated:
            return False
        return user.pk == self.kwargs['pk'] or user.is_superuser



# Create your views here.
class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'main/login.html'

class Top(LoginRequiredMixin, TemplateView):
    template_name = 'main/top.html'

    def get(self, request):
        return redirect('main:profile', request.user.pk)

class Logout(LogoutView):
    pass

    
class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy('main:login')
    template_name = 'main/signup.html'
    
    def form_valid(self, form):
        ret = super().form_valid(form)
        messages.success(self.request, f'ユーザ:{self.object.username} 登録完了しました。')
        return ret

from .models import category1s, category2s
class ListCompany(ListView):
    model = User
    template_name = 'main/list_company.html'
    paginate_by = 3
    
    def get_context_data(self, **kwargs):
        total_count = self.get_queryset().count()
        c = super().get_context_data(**kwargs)
        c['total_count'] = total_count
        c['category1s'] = category1s
        c['category2s'] = category2s
        c1 = self.request.GET.getlist('category1s')
        c2 = self.request.GET.getlist('category2s')
        c['query_params'] = { 
            'category1s': c1,
            'category2s': c2,
            'query': self.request.GET.get('query', '')
        }
        print(c['total_count'])
        return c

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-pk')
        c1 = self.request.GET.getlist('category1s')
        c2 = self.request.GET.getlist('category2s')
        query = self.request.GET.get('query', None)
        if len(c1) > 0:
            queryset = queryset.filter(category1__in = c1)
        if len(c2) > 0:
            queryset = queryset.filter(category2__in = c2)
        if query:
            queryset = queryset.filter(company_name__icontains = query)
        return queryset

class DetailCompany(DetailView):
    model = User
    template_name = 'main/detail_company.html'
    
class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm   
    template_name = 'main/profile.html'
    def get_success_url(self):
        return reverse_lazy('main:profile', kwargs={ "pk": self.kwargs["pk"] })
    
    def form_valid(self, form):
        messages.success(self.request, '登録情報を更新しました')
        return super().form_valid(form)

main/templates/main/admin_base.html
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>ICTCO 管理画面</title>
        <meta name="description" content="Epsilon　会社紹介サイト" />
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body class="bg-gray-50">
        {% include 'main/components/navbar.html' %}
            
        <div class="container mx-auto" style="max-width: 1024px">
            <div class="py-5">
                {% if messages %}
                    {% for message in messages %}
                    <div class="bg-green-400 text-white p-3 text-center">
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>
           
        </div>
        {% include 'main/components/footer.html' %}
    </body>
</html>

main/templates/main/detail_company.html
{% extends 'main/public_base.html' %}
{% load static %}
{% block content %}
<nav class="bg-grey-light p-3 rounded font-sans w-full m-4">
    <ol class="list-reset flex text-grey-dark">
      <li><a href="{% url 'main:list_company' %}" class="text-blue font-bold">会社一覧</a></li>
      <li><span class="mx-2">/</span></li>
      <li>{{ object.company_name }}</li>
    </ol>
</nav>
<div class="bg-white text-black border p-5 mb-5" style="position: relative;">
    <div class="text-xs">{{ object.company_name_furigana }}</div>
    <h1 class="text-3xl font-extrabold mb-2">{{ object.company_name }}</h1>
    <div>
      [業種]大分類：{{ object.category1_name }}　小分類：{{ object.category2_name }}
    </div>
    {% if object.short_delivery %}
    <div style="position: absolute; right: 0; top: 0;">
        {% include 'main/components/short_delivery.html' %}
    </div>
    {% endif %}
</div>
<div class="flex w-full border-b-2 border-black mb-5">
    <div class="bg-black font-bold text-white p-3">
        会社概要
    </div>
</div>
<div class="mb-5" style="min-height: 50px;">
    {{ object.short_descripmtion|linebreaks }}
</div>
<div class="bg-gray-200 text-gray-600 font-bold p-3 mb-5">
    会社案内
</div>
<table class="mb-5 w-full border-collapse text-black border border-gray-200">
    <tbody>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          代表者
        </th>
        <td class="p-4">
          {{ object.representative_name }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          業務内容説明
        </th>
        <td class="p-4">
          {{ object.description|linebreaks }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          電話番号
        </th>
        <td class="p-4">
          {{ object.phone }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          創立
        </th>
        <td class="p-4">
          {{ object.established_at }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          主な取引先
        </th>
        <td class="p-4">
          {{ object.major_clients|linebreaks }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          主な製品
        </th>
        <td class="p-4">
          {{ object.major_products|linebreaks }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          主な技術
        </th>
        <td class="p-4">
          {{ object.major_technologies|linebreaks }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          主な施設
        </th>
        <td class="p-4">
          {{ object.major_facilities|linebreaks }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          アピールポイント
        </th>
        <td class="p-4">
          {{ object.appeal_points|linebreaks }}
        </td>
      </tr>
    </tbody>
</table>
<div class="bg-gray-200 text-gray-600 font-bold p-3 mb-5">
    連絡先
</div>
<table class="w-full border-collapse text-gray-700 border border-gray-200">
    <tbody>
      <tr>
        <th class="p-4 bg-gray-100">
            Email
        </th>
        <td class="p-4">
            {{ object.email }}
            <a class="bg-gray-600 rounded shadow text-white p-2 text-xs " href="mailto:{{ object.email }}">メール送信</a>
        </td>  
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          電話番号
        </th>
        <td class="p-4">
          {{ object.phone }}
        </td>
      </tr>
 
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          担当者名
        </th>
        <td class="p-4">
          {{ object.poc_name }}
        </td>
      </tr>
      <tr class="border border-gray-200">
        <th class="p-4 bg-gray-100">
          Website
        </th>
        <td class="p-4">
          {{ object.website }}
        </td>
      </tr>
    </tbody>
</table>
{% endblock %}

{% block style %}
<style>
    th {
        white-space: nowrap;
    }
</style>
{% endblock %}

main/templates/main/list_company.html
{% extends 'main/public_base.html' %}
{% load static %}
{% load myfilters %}
{% block content %}

<div class="align-center mb-5">
    <img class="w-full" src="{% static 'img/billboard1.jpg' %}" alt="">    
</div>
<div class="mb-5">
    <h1 class="bg-white text-black border border-black px-3 py-2 font-bold">
        条件検索
    </h1>
    <form action="">    
        <table class="w-full border-collapse border bg-white text-black mb-1">
            <tbody>
            <tr class=" border-b">
                <th class="text-left p-3 whitespace-nowrap">
                キーワード
                </th>
                <td class="border-l p-2">
                    <div class="font-bold">
                        大分類
                    </div>
                    <div class="flex flex-wrap category">
                        {% for cat1 in category1s  %}
                            <div class="flex ml-3 items-center">
                                <label for="{{ cat1.0 }}">{{ cat1.1 }}</label>
                                <input class="ml-1" id="{{ cat1.0 }}" type="checkbox" value="{{ cat1.0 }}" {% if cat1.0|ifinlist:query_params.category1s %}checked{% endif %} name="category1s">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="font-bold">
                        小分類
                    </div>
                    <div class="flex flex-wrap category">
                        {% for cat2 in category2s  %}
                            <div class="flex ml-3 items-center">
                                <label for="{{ cat2.0 }}">{{ cat2.1 }}</label>
                                <input class="ml-1" id="{{ cat2.0 }}" type="checkbox" value="{{ cat2.0 }}" {% if cat2.0|ifinlist:query_params.category2s %}checked{% endif %} name="category2s">
                            </div>
                        {% endfor %}
                    </div>
                    
                </td>
            </tr>
            <tr>
                <th>企業名</th>
                <td class="border-l p-1">
                    <input type="text" name="query" class="border rounded p-1 w-full" value="{{ query_params.query}}">
                </td>
            </tr>
            </tbody>
        </table>
        <div class="text-right">
            <button
                type="reset"
                class="border rounded shadow bg-gray-600 text-white px-5 py-1 border-black"
            >
                検索条件クリア
            </button> 
            <button
                type="submit"
                class="border rounded shadow bg-white text-black px-5 py-1 border-black"
            >
                検索
            </button>    
        </div>
    </form>
    
</div>
<div class="w-full border-b-2 mb-2 px-5">
    <div class="flex flex-row justify-between">
        <div>
            <span>全</span>
            <b>{{ total_count }}</b>
            <span>社中</span>
            <b>{{ object_list.count }}</b>
            <span>社表示</span>    
        </div>
        {% include 'main/components/paginator.html' %}
    </div>
</div>
<div>
    {% if not object_list.all %}
        <div>
            検索条件にマッチする企業はありませんでした。
        </div>
    {% endif %}
    {% for company in object_list %}
    <div class="flex md:flex-row sm:flex-row flex-col bg-white p-4 shadow mb-2">
        <div class="flex flex-grow">
            <div class="flex-1">
                <div class="flex mb-5">
                    <h1 class="flex text-black text-2xl font-extrabold">
                        <a href="{% url 'main:detail_company' company.pk %}" class="my-auto mr-2 border-b-2">{{ company.company_name }}</a>
                    </h1>
                    {% if object.short_delivery %}
                        {% include 'main/components/short_delivery.html' %}
                    {% endif %}
                    </div>
                <div class="mb-2 text-sm">
                [業種]大分類：{{ company.category1_name }}　小分類：{{ company.category2_name }}
                </div>
                <div class="mb-1">
                    {{ company.short_description | linebreaks | abstract }}
                </div>
                {% if company.short_description|iflongerthan240 %}
                <div class="mb-5">
                
                    <a href="#" class="border-b-2 text-gray-700 text-sm">
                        続きを読む
                    </a>
                        
                </div>
                {% endif %}
                <div>
                TEL:{{ company.phone }}
                </div>
            </div>
        </div>
        <div class="p-3 text-right">
            {% if company.thumbnail %}
            <img src="{{ company.thumbnail.url }}" style="min-width:180px!important;" alt="">
            {% endif %}
        </div>
    </div>
    {% endfor %}    
</div>
<style>
    .company-card:hover {
        box-shadow:0 6px 14px rgba(0, 0, 0, 0.24);
        transform:translate(0, -2px);
    }
</style>
{% endblock %}

main/templates/main/login.html
{% extends 'main/admin_base.html' %}
{% block content %}
<h1 class="text-center text-3xl font-extrabold">
    管理画面ログイン
</h1>
<div class="bg-white mx-auto mt-5 p-4 shadow" style="max-width: 600px;">
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <div class="text-center">
            <button class="py-2 px-5 bg-white border-2 text-black border-black rounded">ログイン</button>    
        </div>
        <div class="text-center">
            利用登録がお済でない方は<a href="{% url 'main:signup' %}" class="border-b border-blue-600 text-blue-600">こちら</a>
        </div>
    </form>
</div>
{% endblock %}

main/templates/main/profile.html
{% extends 'main/admin_base.html' %}
{% block content %}
<h1 class="text-center text-3xl font-extrabold">
    登録情報修正
</h1>
<div class="bg-white mx-auto mt-5 p-7 shadow" style="max-width: 600px;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <div class="text-center">
            <button class="py-2 px-5 bg-white border-2 border-black rounded text-black">更新</button>        
        </div>
    </form>
</div>
{% endblock %}

main/templates/main/public_base.html
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>ICTCO 会員企業検索</title>
        <meta name="description" content="Epsilon　会社紹介サイト" />
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body class="bg-gray-50">
        {% include 'main/components/navbar.html' %}
        <div class="container mx-auto" style="max-width: 1024px">
            <div class="py-3 px-2">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        {% include 'main/components/footer.html' %}
        {% block style %}
        {% endblock %}
    </body>
</html>

main/templates/main/signup.html
{% extends 'main/admin_base.html' %}
{% block content %}
<h1 class="text-center text-3xl font-extrabold">
    管理画面利用登録
</h1>
<div class="bg-white mx-auto mt-5 p-7 shadow" style="max-width: 600px;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <div style="height: 50px;">
            
        </div>
        <div class="text-center">
            <button class="py-2 px-5 bg-white border-2 text-black border-black rounded">登録</button>    
        </div>
        <div class="text-center">
            すでにご登録済みの方は<a href="{% url 'main:login' %}" class="text-blue-600 border-b border-blue-600">こちら</a>
            
        </div>
    </form>
</div>
{% endblock %}